[package]
name = "fixed_width"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fixed_width_derive = { path = "fixed_width_derive" }
chrono = "0.4.30"
time = "0.3.28"
